[package]
name = "brooke/freeze-tag"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"
LuauPolyfill = "jsdotlua/luau-polyfill@1.2.6"
Sift = "csqrl/sift@0.0.8"
Loader = "sleitnick/loader@2.0.0"
Log = "sleitnick/log@0.1.1"
Signal = "sleitnick/signal@2.0.1"
Component = "sleitnick/component@2.4.8"
Trove = "sleitnick/trove@1.1.0"

[server-dependencies]
Cmdr = "evaera/cmdr@1.9.0"

[dev-dependencies]
Jest = "jsdotlua/jest@3.4.1"
JestGlobals = "jsdotlua/jest-globals@3.4.1"
